### ISSUE TITLE
исправить опечатку "FuelDisplenser" на "FuelDispenser"

### ISSUE THREAD

**Issue by apkuznetsov** [kouznts/software-engineering-2019#12]

**Comment by 1kurepin** [comment]
Чем мотивированно открытие issue?
Не быстрее было бы исправить самому?

**Comment by apkuznetsov** [comment]
> Чем мотивированно открытие issue?
> Не быстрее было бы исправить самому?

не быстрее: нужно вручную переименовывать события

**Comment by 1kurepin** [comment]
Странно, что нет автопереименования
А вообще есть же "Find and Replace"

**Comment by 1kurepin** [comment]
Исправлено
