### ISSUE TITLE
Переход к моделированию АЗС

### ISSUE THREAD

**Issue by 1kurepin** [kouznts/software-engineering-2019#19]
- [x] Для Моделирования топологии необходимо получить от Конструктора массив объектов интерфейсного типа ITopologyElement.
- [x] Интерфейс содержит метод, возвращающий Point c координатами элемента в матрице конструктора.
<hr>

- [x] Интерфейс реализуют объекты FuelDispenserModel, FuelTankModel, CashCountrerModel, содержащие все необходимую информацию для их моделирования.

<hr>

- [x] Также вместе с данным массивом необходимо передать размер топологии по вертикали и горизонтали, координату  в матрице  въезда, выезда и левой верхней границы служебной области. Кроме того нужно передать все остальные данные для моделирования.
<hr>

- [x] Служебную область нужно сделать фиксированной в правой стороне топологии
<hr>

- [x] Все это нужно запихнуть в один объект и отправить его на моделирование.
Объект назвать по типу "TopologyModel"

**Comment by 1kurepin** [comment]
- [ ] Также передать список объектов Fuel, которые будут использованы

**Comment by apkuznetsov** [comment]
- [x] переход к форме ЗР только после проверки корректности Топологии
- [x] переход к Моделированию только из формы ЗР

**Comment by apkuznetsov** [comment]
сделано
