### ISSUE TITLE
проверка корректности Топологии при Сохранении (и переходе к Моделированию)

### ISSUE THREAD

**Issue by apkuznetsov** [kouznts/software-engineering-2019#20]
- [x] наличие въезда;
- [x] наличие выезда;
- [x] наличие кассы;
- [x] наличие хотя бы одной ТРК
- [x] наличие хотя бы одного бака с одним видом топлива;

**Comment by Leonid-Kurepin** [comment]
У ТРК идет заправка только с одной стороны - снизу. Требования для ТРК:

- все клетки вокруг ТРК свободны
- нельзя размещать по краям, т.е. между ТРК и любым краем есть промежуток хотя бы в одну клетку 

У ТБ заправка идет сбоку - слева . Требования для ТБ:

- осуществить возможность проезда к ТБ

---Пока не уверен

- въезд не позднее по ходу движения, чем первая ТРК

- выезд после или в той же колонке, где последняя ТРК

**Comment by Leonid-Kurepin** [comment]
Требования для кассы: 

- все клетки вокруг Кассы свободны
- может располагаться на границе топологии

**Comment by Leonid-Kurepin** [comment]
Служебная область:

- [ ]  Нижняя строка не занимается служебной областью

**Comment by apkuznetsov** [comment]
переходить к Моделированию только, если эти пункты выполняются

**Comment by apkuznetsov** [comment]
сделано
