### ISSUE TITLE
отрефакторить ресурсы

### ISSUE THREAD

**Issue by apkuznetsov** [kouznts/software-engineering-2019#26]
```
    <None Include="Resources\icons8-oil-storage-tank-64_photo-resizer.ru.png" />
    <None Include="Resources\icons8-oil-storage-tank-641.png" />
    <None Include="Resources\fuel1.ico" />
    <None Include="Resources\fuel1.jpg" />
    <None Include="Resources\Blank.png" />
    <None Include="Resources\icons8-cash-counter-64.png" />
    <None Include="Resources\fuel.jpg" />
    <None Include="Resources\icons8-oil-storage-tank-64.png" />
    <None Include="Resources\FuelTank.ico" />
    <None Include="Resources\fuel.ico" />
```
- длинное название ресурсов (95, 96, 100, 102)
- ресурсы с одинаковыми именами (97, 98, 101, 104) (во избежание путаницы для изображения Fuel нужен только один ресурс)
- предлагаю писать названия всех ресурсов с большой буквы (единый стиль программирования)
- удалить все лишние ресуры

**Comment by Leonid-Kurepin** [comment]
- нужна отдельная папка с картинками машин, внутри которой будут отдельные папки для каждой картинки, повёрнутой в различные стороны

**Comment by kouznts** [comment]
помойка, в которой тяжело разобраться

**Comment by kouznts** [comment]
помойка, которая сломала логику добавления ШЭ

**Comment by apkuznetsov** [comment]
архив
