### ISSUE TITLE
Дрожание машин при их сближении 

### ISSUE THREAD

**Issue by 1kurepin** [kouznts/software-engineering-2019#30]
### Когда машина пытается врезаться в другую, она дрожит

Происходит из-за того, что сначала она отрисовывается с наложением на вторую машину, а потом срабатывает логика ее отбрасывания к границам этой машины

**Вариант реализации:** 

Каждой машине присвоить невидимый пикчер бокс SaveArea
Сначала будет двигаться SaveArea, и если никаких препятствий по ходу движения нет, то машина продвигается, иначе возвращаем SaveArea на место и не двигаем машину

<hr>
То же самое можно реализовать для логики сближения с любыми объектами, для более красивой графики.

Однако там это некритично - при столкновении не с машинами эффект мерцания совсем не бросается в глаза.

**Comment by apkuznetsov** [comment]
архив
