### ISSUE TITLE
процесс работы с базой данных (БД)

### ISSUE THREAD

**Issue by apkuznetsov** [kouznts/software-engineering-2019#9]
### Автомобиль:
- [x] название
- [x] объём бака
- [x] вид топлива
- [x] класс
- [ ] У легковых автомобилей объем бака может быть от 50 до 100 л.
- [ ] грузовых автомобилей объем бака может быть от 125 до 600 л
- [ ] 35) минимальный объем бака легкового автомобиля – 50 л;
--------------------------------------------------------
- [ ] 1 добавление записи
- [ ] 2 удаление записи
- [ ] 3 редактирование записи
--------------------------------------------------------
- [ ] Цена за литр топлива может быть установлена от 10 рублей до 100 рублей.
- [ ] 36) максимальный объем бака легкового автомобиля – 100 л;
- [ ] 37) минимальный объем бака грузового автомобиля – 125 л;
- [ ] 1) максимальный объем бака грузового автомобиля – 600 л;
- [ ] 2) количество видов транспорта – 2.

**Comment by 1kurepin** [comment]
В базе сейчас нет Автомобилей вообще.

То, что лежит в GasStationMs.Dal, Bll и CommonLayer является реализацией БД на отдельном сервере и не используется.

**Comment by 1kurepin** [comment]
@kouznts

-  редактирование записей не предусмотрено на данный момент. Нужно ли? Я бы не хотел делать

- делайте все ограничения в UI

**Comment by apkuznetsov** [comment]
> * редактирование записей не предусмотрено на данный момент. Нужно ли? Я бы не хотел делать

@Leonid-Kurepin редактирование записи есть в ПЗ

**Comment by 1kurepin** [comment]
Без предварительного запроса от Зеленко редактирование топлива предлагаю не делать.

**Comment by apkuznetsov** [comment]
было реализовано
